Task 4
paderinandrey/th-react pull request #6
Opened 2018-08-09 00:10 UTC by paderinandrey

2018-08-09 13:08 UTC, index01d requested changes

2018-08-09 13:08 UTC, index01d commented on src/components/CartButton.js
> +              Cart ({cart.length})
это точно работает?

2018-08-09 13:08 UTC, index01d commented on src/components/CartButton.js
> +      this.props.history.push(rootPath(), { message: "Your cart is currently empty. Please add some products to cart." });
длинновато, стоит разбить на строчки

2018-08-09 13:35 UTC, paderinandrey commented on src/components/CartButton.js
> +              Cart ({cart.length})
Работает 
![image](https://user-images.githubusercontent.com/14351695/43902036-b3a92678-9bf1-11e8-9662-6ea1e0786589.png)
`cart` это же у меня массив, хранящийся в `CartProvider`.

2018-08-10 13:27 UTC, index01d requested changes

2018-08-10 13:27 UTC, index01d commented on src/components/CartButton.js
> +      this.props.history.push(rootPath(), { message: "Your cart is currently empty. Please add some products to cart." });
можно было бы реализовать читабельнее с использованием компонента Redirect и условного вывода (см https://reacttraining.com/react-router/web/api/Redirect) в методе render страницы корзины, иначе этот handler придется всюду дублировать

2018-08-12 08:24 UTC, index01d approved these changes

2018-08-12 11:30 UTC, merged